### ISSUE TITLE
ActiveRecord attributes and validation errors translations

### ISSUE THREAD

**Issue by aitbw** [ai/r18n#140]
Hello!

I'm currently working on a project based on Sinatra and ActiveRecord and I'm translating it as we speak.

How can I translate ActiveRecord attributes and validations errors with this stack? My es.yml for validations errors has the following structure:

```yaml
activerecord:
  errors:
    format: "%{attribute} %{message}"
    messages:
      blank: no puede estar vacío
      taken: ya se encuentra en uso
      not_a_number: no es un número
      too_short:
        other: es muy corta (mínimo de %{count} caracteres)
      too_long:
        other: es muy larga (máximo de %{count} caracteres)
```

I have read your documentation for r18n-core, r18n-rails and r18n-rails-api but it's unclear for me how can I achieve this.
