### ISSUE TITLE
R18n-core disturbs YAML::ENGINE

### ISSUE THREAD

**Issue by RmMsr** [ai/r18n#80]
Hi,

I just noticed a problem that seems to be related to the way R18n loads YAML.

This code

``` ruby
#!/usr/bin/env ruby
require 'yaml'
require 'r18n-core'
#YAML::ENGINE.yamler = 'syck'
#YAML::ENGINE.yamler = 'psych'
puts "TEST".to_yaml
```

results to

``` yaml
--- !ruby/object:String
taguri: ! '!ruby/object:String'
to_yaml_style: 1
```

If the yamler is set to either `syck`or `psych`after loading R18n, everything works fine.

Running `ruby 1.9.3p194 (2012-04-20 revision 35410) [x86_64-darwin10.8.0]` with `r18n-core (1.1.0)`
