### ISSUE TITLE
Question: How to access an array of keys from within a helper or template?

### ISSUE THREAD

**Issue by davesag** [ai/r18n#96]
Assume I have a translation file like `en.yml`

```
title:
  mr: Mr
  ms: Ms
  mrs: Mrs
  miss: Miss
  dr: Dr
  prof: Prof.
```

I'd like to use a bit of code in my `slim` template like

```
select#title name="title"
  -for ti in t.title.keys
    option value=title = t.title[ti]
```

to create my list of titles in  popup menu.

however `t.title.keys` isn't returning an array of keys as I hoped.

Is there an official way to return the array of keys from a translation file?

Cheers

Dave
